name = "software-foundations-lean"
version = "0.1.0"
defaultTargets = ["SoftwareFoundationsVol1", "SoftwareFoundationsVol2"]

[[lean_lib]]
name = "SoftwareFoundationsVol1"

[[lean_lib]]
name = "SoftwareFoundationsVol2"
